### ISSUE TITLE
Typescript Unable to resolve signature of parameter of decorator in vscode

### ISSUE THREAD

**Issue by luluhoc** [microsoft/vscode-typescript-next#72] opened 2023-01-25 09:58 UTC
Seems that the extension is broken

v5.0.202301230

I'm getting the error when I'm decorating the class in nestjs service.
I'm using typescript 4.9.4

The Typescript is compiling without errors, and I'm getting this problem only in VSCode.

```
Unable to resolve signature of parameter decorator when called as an expression.
  Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.ts(1239)
```

My tsconfig
```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "strictNullChecks": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2020",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
  }
}

```

My Class
```
export class AuthService {
  private readonly logger = new Logger('AuthService');
  constructor(
    private readonly jwtService: JwtService,
    private readonly prisma: PrismaService,
    private readonly passwordService: PasswordService,
    private readonly configService: ConfigService,
    private readonly twilioService: TwilioService,
    private readonly userService: UsersService,
    @InjectQueue('nest-worker') private nestWorkerQueue: Queue,
    @InjectQueue('mailsend') private mailSend: Queue,
    @Inject(CACHE_MANAGER) protected readonly cacheManager: Cache,
    private readonly mailerService: MailService
  ) {}

```

Disabling the Extention solves the problem

**Comment by mjbvz** [comment] 2023-01-25 21:03
Closing as a duplicate of this already opened TS issue

**Closed by mjbvz** 2023-01-25 21:03 UTC
