### ISSUE TITLE
Additional characters at the end of autofill suggestions

### ISSUE THREAD

**Issue by saikun0293** [microsoft/vscode-typescript-next#69] opened 2023-01-18 13:35 UTC
Type: **Bug**

OS : Windows 11
Extension Version: v5.0.202301160
VSCode Version: 1.74.3

On enabling the extension, the autofill suggestions seem to add characters at the end on pressing enter like so.

Before
![image](https://user-images.githubusercontent.com/56252312/213183705-b36a3bd9-295f-4019-9df2-d00e3593d9f6.png)

After
![image](https://user-images.githubusercontent.com/56252312/213183842-58b5b765-1790-48e4-8d4e-d2b108cacf8e.png)
*Adds ="" incase the variable is of type string*

On disabling the extension, it works properly again. Figured it might the issue on using the extension.

**Comment by mjbvz** [comment] 2023-01-18 16:54
Duplicate of #66

**Closed by mjbvz** 2023-01-18 16:54 UTC
