### ISSUE TITLE
Syntax highlighting all white!

### ISSUE THREAD

**Issue by Eumhongin** [microsoft/vscode-typescript-next#54] opened 2022-11-17 09:27 UTC
highlighting gone!

**Comment by whqgo** [comment] 2022-11-17 09:44
I've disabled them

**Comment by devGumidafe** [comment] 2022-11-17 09:51
I think this is caused by the extension called Javascript and Typescript Nightly. So disable the extension.

**Comment by mael-queau** [comment] 2022-11-17 09:57
I believe it would be wiser to "install another version and use the one directly before the current one, so as not to remove everything all at once.

Like this:

![image](https://user-images.githubusercontent.com/100228262/202415330-e1cc8f3a-8b8e-4034-9d62-9faba4d1f6b1.png)

![image](https://user-images.githubusercontent.com/100228262/202415477-b4e64430-7788-40ae-96d9-4df3557baa3a.png)

**Comment by xiechanglei2022** [comment] 2022-11-17 10:01
I noticed that the highlighting for javascript file  in my editor is missing，and it cost 3 hours before I came here.

**Comment by mjbvz** [comment] 2022-11-17 15:44
Duplicate of #43

**Closed by mjbvz** 2022-11-17 15:44 UTC
