### ISSUE TITLE
Disables semantic highligthing for javascript and vue file

### ISSUE THREAD

**Issue by eroglu94** [microsoft/vscode-typescript-next#49] opened 2022-11-17 05:31 UTC
Type: <b>Bug</b>

VsCode most of the semantic highlighting is lost when extension is open.

Also "Developer: Inspect Editor Tokens and Scopes" throws error when extension is active.
Thrown Error : "No TM Grammar registered for this language"

if extension enabled;
![image](https://user-images.githubusercontent.com/11258914/202364738-a70ddfdc-1dc9-492a-b20d-1ecb61305cfe.png)

when extension disabled;
![image](https://user-images.githubusercontent.com/11258914/202364814-63ebbf79-a90b-427d-9a36-1d3018b3f4cc.png)

Extension version: 5.0.20221116
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.52GB free)|
|Process Argv|--crash-reporter-id ea3b7209-2e58-4bce-85b0-4b1a77c81874|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30602488
gswce1:30612156
iaj6b796:30608729
dbltrim-noruby:30604474

```

</details>

**Comment by bendalton** [comment] 2022-11-17 05:47
I too had this issue occur but all syntax highlighting for javascript was disabled and I used the "extension bisect" feature to determine this was the plugin causing the problem. It worked well before a recent update.

**Comment by sahilchraya** [comment] 2022-11-17 05:48
Same problem. Recent update just killed it.

**Comment by avwave** [comment] 2022-11-17 05:54
can confirm,  reverting the extension to 5.020221115 enables syntax highlighting again

**Comment by cheny-github** [comment] 2022-11-17 06:24
I get same problem

**Comment by rhenaldkarrel** [comment] 2022-11-17 06:31
Downgrading to the previous version solved it for me

**Comment by zedd3v** [comment] 2022-11-17 06:38
https://github.com/microsoft/vscode/issues/166541

Happening for a lot of people

**Comment by Brenndoerfer** [comment] 2022-11-17 06:47
Same here. As suggested, installing a previous version worked for me too.

Click on the arrow next to `Uninstall` -> `Install another version` and select the previous build (or any that works for you)
![image](https://user-images.githubusercontent.com/3137248/202375816-930ac64c-be3d-473e-8e2c-60b6300011b2.png)

**Comment by mjbvz** [comment] 2022-11-17 15:45
Duplicate of #43

**Closed by mjbvz** 2022-11-17 15:45 UTC
