### ISSUE TITLE
Syntax Color Disappeared Hours After Updating

### ISSUE THREAD

**Issue by SS-Runen** [microsoft/vscode-typescript-next#50] opened 2022-11-17 06:46 UTC
Type: <b>Bug</b>

- Open a TypeScript project with JavaScript and TypeScriptNightly 5.0.20221115 installed.
- Update to 5.0.20221116 or enable automatic updates.
- Immediately after or a few hours after updating, strings and some key words are plain white instead of brownish (strings) or violet (return and try-catch keywords).

Extension version: 5.0.20221116
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
OS version: Linux x64 5.19.0-23-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 4017)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.57GB (9.35GB free)|
|Process Argv|--unity-launch /home/joachim/Documents/GitLab/Deer - Megaworld Malls/core-service --crash-reporter-id 719195a2-a56d-4528-91ed-a3bfe461d2ef|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by krupeshanadkat-byjus** [comment] 2022-11-17 06:51
Facing same issues

**Comment by SS-Runen** [comment] 2022-11-17 06:54
Downgrading to JS and TS Nightly 5.0.20221115 also fixed the problem. I still don't know why it happens. Thankfully, it is not a critical bug.

**Comment by pranay1208** [comment] 2022-11-17 07:03
> Downgrading to JS and TS Nightly 5.0.20221115 also fixed the problem. I still don't know why it happens. Thankfully, it is not a critical bug.

This solution worked for me as well. 

Had to hard reinstall VSCode on my machine before I figured out this was the problem

**Comment by jeffrey125** [comment] 2022-11-17 07:18
Same here I've been finding a way to fix this bug and after several hours downgrading it to the last version made it work again.

I think there's a problem in the current build of the extension

**Comment by liuliangsir** [comment] 2022-11-17 07:27
Same issue here

**Comment by Metarock** [comment] 2022-11-17 07:37
Facing the same issue here, had to disable it.

**Comment by ai-chen2050** [comment] 2022-11-17 07:43
<img width="914" alt="image" src="https://user-images.githubusercontent.com/27693952/202385542-0a81e55e-3870-489e-ab17-41594b173adc.png">
despair spends much time to find this. 😭

**Comment by yamachu** [comment] 2022-11-17 08:26
```
$ lla 1115/syntaxes/*
.rw-r--r-- yk-yamada staff 214 KB Thu Nov 17 17:21:33 2022  1115/syntaxes/JavaScript.tmLanguage.json
.rw-r--r-- yk-yamada staff 216 KB Thu Nov 17 17:21:33 2022  1115/syntaxes/JavaScriptReact.tmLanguage.json
.rw-r--r-- yk-yamada staff 217 KB Thu Nov 17 17:21:33 2022  1115/syntaxes/TypeScript.tmLanguage.json
.rw-r--r-- yk-yamada staff 214 KB Thu Nov 17 17:21:33 2022  1115/syntaxes/TypeScriptReact.tmLanguage.json
$ lla 1116/syntaxes/*
.rw-r--r-- yk-yamada staff 0 B Thu Nov 17 17:20:52 2022  1116/syntaxes/JavaScript.tmLanguage.json
.rw-r--r-- yk-yamada staff 0 B Thu Nov 17 17:20:52 2022  1116/syntaxes/JavaScriptReact.tmLanguage.json
.rw-r--r-- yk-yamada staff 0 B Thu Nov 17 17:20:52 2022  1116/syntaxes/TypeScript.tmLanguage.json
.rw-r--r-- yk-yamada staff 0 B Thu Nov 17 17:20:52 2022  1116/syntaxes/TypeScriptReact.tmLanguage.json
```

syntax files are empty on 20221116 :(

**Comment by J-Dany** [comment] 2022-11-17 08:43
Disabling the extension **JavaScript and TypeScript Nightly** didn't resolve for me.

**Comment by padunk** [comment] 2022-11-17 09:02
![Screen Shot 2022-11-17 at 13 38 18](https://user-images.githubusercontent.com/25411350/202402123-d4bbe167-a0dd-4819-a3a7-e993c11356f2.png)

This extension is causing the issue. so either disable it or downgrade it back to `...15`

**Comment by mjbvz** [comment] 2022-11-17 15:45
Duplicate of #43

**Closed by mjbvz** 2022-11-17 15:45 UTC
