### ISSUE TITLE
Update Breaks Syntax Highlighting

### ISSUE THREAD

**Issue by currenthandle** [microsoft/vscode-typescript-next#47] opened 2022-11-17 03:41 UTC
v. 5.0.20221116 breaks syntax highlighting in TSX files. When from looking like this:
<img width="518" alt="Screenshot 2022-11-16 at 7 37 57 PM" src="https://user-images.githubusercontent.com/10948068/202349130-00cdfde4-3a21-4e58-84bc-85cb5c6117b1.png">

to looking like this:
<img width="606" alt="Screenshot 2022-11-16 at 7 38 15 PM" src="https://user-images.githubusercontent.com/10948068/202349162-384c501f-6bc9-45c7-9beb-0ac75994f2bf.png">

The most obvious to see is the arrow function's `=>` has two different colors.

To reproduce: right-click extension in extensions menu, select "Install Another Version...", and install v. 5.0.20221115, and it should work as expected

Mac OS Ventura 10.3 x/ M1 Max
Visual Studio Code 1.73.1

**Comment by SlavMAK** [comment] 2022-11-17 03:56
Version v5.0.20221116 breaks syntax highlighting.
![image](https://user-images.githubusercontent.com/15261189/202351247-09750c32-004e-4d86-89b0-1bf28bec38f1.png)

Temporarily disabled the plugin. It turned out like this:
![image](https://user-images.githubusercontent.com/15261189/202351327-e1b72854-c75e-4ce4-8bbe-c79ad666d8a7.png)

**Comment by SlavMAK** [comment] 2022-11-17 04:08
A duplicate of the issue (#46  #48  #43  #45  #44 ). A temporary solution is to install the previous version.

**Closed** 2022-11-17 04:20 UTC
