### ISSUE TITLE
TypeScript React's default autocomplete uses wrong syntax `{item={}}`

### ISSUE THREAD

**Issue by vozaldi** [microsoft/vscode-typescript-next#71] opened 2023-01-24 04:01 UTC
Hello, I just reported [an issue (#172105)](https://github.com/microsoft/vscode/issues/172105) in main VSCode repo. And after a bit of testing, I figured out the issue was caused by JavaScript and TypeScript Nightly plugin.

I have tested this in VSCode Insiders with only one plugin enabled, **JavaScript and TypeScript Nightly**.

### How to Reproduce

1. Declare a type using object structure.
```
type Model = {
  id?: number;
  type?: string;
};
```

2. Declare the type as an Array.
```
const models: Model[] = [{
  id: 1,
  type: 'model',
}];
```

3. Spread the array using `.map` function. As you type `{item` the autocomplete pop up appeared and suggested `item --- (parameter) item: Model` on the first line.
```
{models.map((item, index) => (
  <span>{item // Autocomplete pops up
)}
```

4. When the first line of autocomplete selected it becomes `{item={}}`. Which is suggesting to *assign* values instead of *declaring* the values.

5. Expected behaviour from No. 3 is the autocomplete from `{item ..` becomes `{item.id}` not `{item={}}`

![This is an image](https://drive.google.com/uc?export=view&id=1NyVg1anD1mfvxC01xI0Lh11iDr_sRZxg)

---

#### Plugin info

**JavaScript and TypeScript Nightly**

```
Published - 6/11/2019, 05:23:13
Last released - 1/24/2023, 07:17:39
Last updated - 1/24/2023, 10:43:29
Identifier - ms-vscode.vscode-typescript-next
```

Reference [VSCode issue #172105](https://github.com/microsoft/vscode/issues/172105)

**Comment by mjbvz** [comment] 2023-01-24 06:57
Duplicate of https://github.com/microsoft/TypeScript/issues/52288

**Closed by mjbvz** 2023-01-24 06:57 UTC
