### ISSUE TITLE
Syntax highlighting issues are not available.

### ISSUE THREAD

**Issue by mxyhi** [microsoft/vscode-typescript-next#53] opened 2022-11-17 09:16 UTC
The latest version has syntax highlighting issues. Syntax highlighting is not possible.

**Comment by mael-queau** [comment] 2022-11-17 09:58
I believe the only workaround currently available is reverting to a previous version:

https://github.com/microsoft/vscode-typescript-next/issues/54#issuecomment-1318377433

**Comment by mjbvz** [comment] 2022-11-17 15:44
Duplicate of #43

**Closed by mjbvz** 2022-11-17 15:44 UTC
