### ISSUE TITLE
After the new update, editor text color became strange.

### ISSUE THREAD

**Issue by bdabin** [microsoft/vscode-typescript-next#44] opened 2022-11-17 01:38 UTC
2022.11.17 AM 09 : 10 (UTC+9)
After the new update, editor text color became strange. (in VSCODE. other files too)

![스크린샷 2022-11-17 오전 10 37 40](https://user-images.githubusercontent.com/52160703/202332631-a8f8a03d-c7bf-401d-9f21-8821cbe1e10e.png)
![스크린샷 2022-11-17 오전 10 37 54](https://user-images.githubusercontent.com/52160703/202332688-f72e0c7f-9e1c-480b-8789-3c48dcd8ee2b.png)

**Comment by Maxigong** [comment] 2022-11-17 02:09
Same issue here.

**Comment by effs** [comment] 2022-11-17 02:41
Same as #43, downgrade to yesterday's version to temp fix

**Comment by itsramiel** [comment] 2022-11-17 13:47
How do you downgrade?

**Comment by mjbvz** [comment] 2022-11-17 15:43
Duplicate of #43

**Closed by mjbvz** 2022-11-17 15:43 UTC
