### ISSUE TITLE
 React, Typescript syntax highlighting is not after enabling JavaScript and TypeScript Nightly extension

### ISSUE THREAD

**Issue by pradeep026** [microsoft/vscode-typescript-next#48] opened 2022-11-17 03:56 UTC
Hi,

I upgraded my VS Code version to latest "1.73.1"
After upgrading vscode, I noticed my syntax highlighting is not working.
But, the syntax highlighting is working when I disable or uninstall `JavaScript and TypeScript Nightly` extension.

System: MAC M2
OS: macOS Monterey

Syxtax highlight when the extension is enabled

<img width="608" alt="Screenshot 2022-11-17 at 11 55 35 AM" src="https://user-images.githubusercontent.com/7710372/202351295-16f1b3ec-8a34-4a7f-a98a-7fae03f4a887.png">

Syntax highlight when the extension is disabled / uninstalled

<img width="575" alt="Screenshot 2022-11-17 at 11 55 24 AM" src="https://user-images.githubusercontent.com/7710372/202351304-24443a6b-acf0-439f-96c7-ec779a9dec4f.png">

Please let me know if there any workaround or fix ?

Thank you

**Comment by Ponpon55837** [comment] 2022-11-17 04:00
I also have this problem and rollback to another version. Need help for new version

**Comment by fahmij8-tkp** [comment] 2022-11-17 04:13
duplicate here https://github.com/microsoft/vscode-typescript-next/issues/43

**Comment by Saadkhalid913** [comment] 2022-11-17 04:24
I have been having this problem as well, fairly recent, only started to occur today. Had to disable the extension

**Comment by ShmilyLin** [comment] 2022-11-17 04:28
I have been having this problem

**Comment by jcerone** [comment] 2022-11-17 04:42
I'm running into the same issue. Downgrading the version worked for me per this discussion: https://github.com/Microsoft/vscode-react-native/issues/111

**Comment by Itsnotaka** [comment] 2022-11-17 04:53
Downgrading the version to the previous one works for me.

**Comment by mjbvz** [comment] 2022-11-17 15:45
Duplicate of #43

**Closed by mjbvz** 2022-11-17 15:45 UTC
