### ISSUE TITLE
Broken syntax highlighting on generics that span more than 1 line.

### ISSUE THREAD

**Issue by walston** [microsoft/vscode-typescript-next#113] opened 2024-02-27 18:48 UTC
Hello
I work a lot with @reduxjs/toolkit and have been annoyed for a while by the broken syntax highlighting on generic functions as object values.

in the screenshot below, you can see that the closing `>` for the generic arguments highlights red, then the `=>` gets broken as well. This seems to only affect object values, and the syntax highlighting has no problem handling the same when assigned to a simple variable.

![Screenshot 2024-02-27 at 10 45 59 AM](https://github.com/microsoft/vscode-typescript-next/assets/10055135/f5abccb1-8df9-4a1e-84bf-fdc0feb457f4)

The screenshot is from VS Code with all extensions disabled, so I believe this is an issue with the base syntax highlighter.

Thanks in advance.

**Comment by mjbvz** [comment] 2024-03-18 21:06
Not caused by this extension. Duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/903 / others in that repo

**Closed by mjbvz** 2024-03-18 21:06 UTC
